Garage3/Models/Members.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Garage3.Models
{
    public class Members
    {
        public int Id { get; set; }

        [Display(Name = "Personal Number")]
        [Range(10,12)]
        public string PersonNr { get; set; }

        [Display(Name = "First Name")]
        public string FristName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string FullName => $"{FristName} {LastName}";
        public ICollection<Vehicles> Vehicles { get; set; }
    }
}

Garage3/Models/ViewModels/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Garage3.Models.ViewModels
{
    public class DetailsViewModel

    {
        public int Id { get; set; }

        public bool Parking = true;

        [Display(Name = "Registration Number")]
        public string RegNumber { get; set; }

        [Display(Name = "Time of Parking")]
        [DisplayFormat(DataFormatString = "{0:f}")]
        public DateTime TimeOfParking { get; set; }
        public string Color { get; set; }

        [Display(Name = "Number of Wheels")]
        [Range(0, 10, ErrorMessage = "No more than 10 Wheels")]
        public int NumberOfWheels { get; set; }

        [Display(Name = "Vehicle Brand")]
        public string Brand { get; set; }

        [Display(Name = "Vehicle Model")]
        public string Model { get; set; }

        public string TypeOfVehicle { get; set; }


        public string FullName { get; set; }

        //Forigen Keys
        public int VehicleTypeId { get; set; }
        public int MemberId { get; set; }

       

        //Navigation Properties

        public VehicleTypes VehicleTypes { get; set; }

        [Display(Name = "The Owner")]
        public Members Members { get; set; }
    }
}

Garage3/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Bogus;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage3.Data;
using Garage3.Models;
using Garage3.Models.ViewModels;

namespace Garage3.Controllers
{
    public class MembersController : Controller
    {
        private readonly Garage3Context _context;
        private readonly IMapper mapper;

        public MembersController(Garage3Context context, IMapper mapper)
        {
            _context = context;
            this.mapper = mapper;
        }
        public async Task<IActionResult> Filter(string PersonalNumber, int? vehicleType)
        {

            var model = string.IsNullOrWhiteSpace(PersonalNumber) ?
                   _context.Members :
                    _context.Members.Where(rn => rn.PersonNr
                                 .Contains(PersonalNumber));
            


            return View(nameof(Index), await model.ToListAsync());
        }

        // GET: Members1
        public async Task<IActionResult> Index()
        {
            return View(await _context.Members.ToListAsync());
        }

        // GET: Members1/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var members = await _context.Members
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (members == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(members);
        //}
        public async Task<IActionResult> Details(int? id)
        {
            var vehicle = await mapper.ProjectTo<MemberDetailsViewModel>(_context.Members)
                .FirstOrDefaultAsync(s => s.Id == id);

            return View(vehicle);
        }



        // GET: Members1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PersonNr,FristName,LastName")] Members members)
        {
            
            if (ModelState.IsValid)
            {
                var findPersonNumber = _context.Members
                    .Where(rn => rn.PersonNr == members.PersonNr).ToList();
                if (findPersonNumber.Count == 0)
                {
                    _context.Add(members);
                }
                else
                {
                    ModelState.AddModelError("PersonNr", "Member with same Person Number already Exist");
                    return View();

                }
                
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           return View(members);
        }

        // GET: Members1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members.FindAsync(id);
            if (members == null)
            {
                return NotFound();
            }
            return View(members);
        }

        // POST: Members1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PersonNr,FristName,LastName")] Members members)
        {
            if (id != members.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(members);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MembersExists(members.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(members);
        }

        // GET: Members1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var members = await _context.Members
                .FirstOrDefaultAsync(m => m.Id == id);
            if (members == null)
            {
                return NotFound();
            }

            return View(members);
        }

        // POST: Members1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var members = await _context.Members.FindAsync(id);
            _context.Members.Remove(members);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MembersExists(int id)
        {
            return _context.Members.Any(e => e.Id == id);
        }
    }
}

Garage3/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage3.Data;
using Garage3.Models;
using Garage3.Models.ViewModels;
using AutoMapper;

namespace Garage3.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly Garage3Context _context;
        private readonly IMapper mapper;

        public VehiclesController(Garage3Context context, IMapper mapper)
        {
            _context = context;
            this.mapper = mapper;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index(string sortOrder)
        {

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var model = mapper.ProjectTo<DetailsViewModel>(_context.Vehicles);
                          
            switch (sortOrder)
            {
                case "name_desc":
                    model = model.OrderByDescending(s => s.RegNumber);
                    break;
                case "Date":
                    model = model.OrderBy(s => s.TimeOfParking);
                    break;
                case "date_desc":
                    model = model.OrderByDescending(s => s.TimeOfParking);
                    break;
                default:
                    model = model.OrderBy(s => s.RegNumber);
                    break;
            }
            //model = await mapper.ProjectTo<DetailsViewModel>(_context.Vehicles).ToListAsync();
            //model = model.Where(s => s.Parking == true);
                    

            return View(await model.ToListAsync());

        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicles = await _context.Vehicles
                .Include(p => p.Members)
                .Include(p => p.VehicleTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicles == null)
            {
                return NotFound();
            }

           
            return View(vehicles);
        }

        // GET: Vehicles/Create
        public IActionResult Park()
        {
            ViewData["MembersId"] = new SelectList(_context.Set<Members>(), "Id", "FullName");
            ViewData["VehicleTypesId"] = new SelectList(_context.Set<VehicleTypes>(), "Id", "TypeOfVehicle");
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Park([Bind("Id,RegNumber,TimeOfParking,Color,NumberOfWheels,Brand,Model,VehicleTypesId,MembersId")] Vehicles vehicles)
        {
            if (ModelState.IsValid)
            {
                vehicles.TimeOfParking = DateTime.Now;

                // Check whether the Vehicle with same Registration Number is Parked or not
                var findRegistrationNr = _context.Vehicles
                    .Where(rn => rn.RegNumber == vehicles.RegNumber).ToList();
                if (findRegistrationNr.Count == 0)
                {
                    _context.Add(vehicles);
                }
                else
                {
                    ModelState.AddModelError("RegNumber", "Vehicle with same Registration Number is already Parked");
                    ViewData["MembersId"] = new SelectList(_context.Set<Members>(), "Id", "FullName");
                    ViewData["VehicleTypesId"] = new SelectList(_context.Set<VehicleTypes>(), "Id", "TypeOfVehicle");
                    return View(vehicles);

                }
               
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MembersId"] = new SelectList(_context.Set<Members>(), "Id", "FullName");
            ViewData["VehicleTypesId"] = new SelectList(_context.Set<VehicleTypes>(), "Id", "TypeOfVehicle");
            return View(vehicles);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicles = await _context.Vehicles.FindAsync(id);
            if (vehicles == null)
            {
                return NotFound();
            }
            ViewData["MembersId"] = new SelectList(_context.Set<Members>(), "Id", "Id", vehicles.MembersId);
            ViewData["VehicleTypesId"] = new SelectList(_context.Set<VehicleTypes>(), "Id", "Id", vehicles.VehicleTypesId);
            return View(vehicles);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RegNumber,Color,NumberOfWheels,Brand,Model,VehicleTypesId,MembersId")] Vehicles vehicles)
        {
            if (id != vehicles.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var editPostData = await _context.Vehicles.FindAsync(id);
                    if (editPostData == null)
                    {
                        return NotFound();

                    }
                    else
                    {
                        
                        editPostData.RegNumber = vehicles.RegNumber;
                        editPostData.Color = vehicles.Color;
                        editPostData.Brand = vehicles.Brand;
                        editPostData.Model = vehicles.Model;
                        editPostData.NumberOfWheels = vehicles.NumberOfWheels;

                        await _context.SaveChangesAsync();
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiclesExists(vehicles.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MembersId"] = new SelectList(_context.Set<Members>(), "Id", "Id", vehicles.MembersId);
            ViewData["VehicleTypesId"] = new SelectList(_context.Set<VehicleTypes>(), "Id", "Id", vehicles.VehicleTypesId);
            return View(vehicles);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> UnPark(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicles = await _context.Vehicles
                .Include(v => v.Members)
                .Include(v => v.VehicleTypes)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicles == null)
            {
                return NotFound();
            }

            return View(vehicles);
        }

        // POST: Vehicles/UnPark/5
        [HttpPost, ActionName("UnPark")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnParkConfirmed(int id)
        {
            var vehicles = await _context.Vehicles.FindAsync(id);
            _context.Vehicles.Remove(vehicles);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiclesExists(int id)
        {
            return _context.Vehicles.Any(e => e.Id == id);
        }
        public async Task<IActionResult> DetailView()
        {
            var model = await _context.Vehicles
                .Include(t => t.VehicleTypes)
                .Include(t => t.Members)
                .Select(t => new DetailsViewModel
                {
                    RegNumber = t.RegNumber,
                    TimeOfParking = t.TimeOfParking,
                    Color = t.Color,
                    Brand = t.Brand,
                    NumberOfWheels = t.NumberOfWheels,
                    Model = t.Model,
                    FullName = t.Members.FristName + " " +  t.Members.LastName
                }).ToListAsync();
            return View(model);

        }

        public async Task<IActionResult> Receipt(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles.FirstOrDefaultAsync(m => m.Id == id);


            if (vehicle == null)
            {
                return NotFound();
            }

            ReceiptViewModel model = new ReceiptViewModel();
            model.RegNumber = vehicle.RegNumber;

            var MemberId = vehicle.MembersId;
            var VehicleTypesId = vehicle.VehicleTypesId;
            var memberDetails = await _context.Members.FirstOrDefaultAsync(m => m.Id == MemberId);
            var vehicleTypeDetails = await _context.VehicleTypes.FirstOrDefaultAsync(m => m.Id == VehicleTypesId);

            model.FullName = memberDetails.FullName;
            model.TypeOfVehicle = vehicleTypeDetails.TypeOfVehicle;
            model.CheckInTime = vehicle.TimeOfParking;
            model.CheckOutTime = DateTime.Now;
            var totalTime = model.CheckOutTime - model.CheckInTime;
            var lessThanHr = (totalTime.Seconds > 0) ? 1 : 0;


            if (totalTime.Days == 0)
            {

Garage3/Views/Members/Create.cshtml
@model Garage3.Models.Members

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Members</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonNr" class="control-label"></label>
                <input asp-for="PersonNr" class="form-control" />
                <span asp-validation-for="PersonNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FristName" class="control-label"></label>
                <input asp-for="FristName" class="form-control" />
                <span asp-validation-for="FristName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage3/Views/Members/Delete.cshtml
@model Garage3.Models.Members

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Members</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.PersonNr)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.PersonNr)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.FristName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.FristName)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Garage3/Views/Members/Details.cshtml
@model MemberDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1> Members Details</h1>

<div class="card ">
    
    <hr />
    <dl class="row">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.PersonNr)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.PersonNr)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.FristName)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.FristName)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Vehicles)</dt>
        <dd class="col-sm-8">
            @foreach (var vehicle in Model.Vehicles)
            {

            <a asp-controller="Vehicles" asp-action="Details" asp-route-id="@vehicle.Id">
                @vehicle.RegNumber
            </a><br />
                 
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Garage3/Views/Members/Edit.cshtml
@model Garage3.Models.Members

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Members</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PersonNr" class="control-label"></label>
                <input asp-for="PersonNr" class="form-control" />
                <span asp-validation-for="PersonNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FristName" class="control-label"></label>
                <input asp-for="FristName" class="form-control" />
                <span asp-validation-for="FristName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage3/Views/Members/Index.cshtml
@model IEnumerable<Garage3.Models.Members>

@{
    ViewData["Title"] = "Index";
}

<h1>Members</h1>

<form asp-action="Filter">
    <div class="input-group m-3">
        <input type="text" name="PersonalNumber" class="form-control" placeholder="Search on Personal Number" />
        @*<div class="input-group-append">
            <select name="Members" asp-items="@Html.GetEnumSelectList<VehicleTypes>()" class="form-control">
                <option selected="selected" value="">Please select</option>
            </select>
        </div>*@
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary"><i class="fa fa-search">&emsp;Search</i></button>
        </div>
    </div>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FristName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FristName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>